# Generated by Django 3.1.1 on 2020-09-21 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=70, unique=True)),
                ('property_type', models.CharField(choices=[('apartments', 'Apartments'), ('arcades', 'Arcades'), ('arena_workshop', 'Arena Workshops'), ('bunkers', 'Bunkers'), ('casino_penthouse', 'Casino Penhouse'), ('command_centers', 'Command Centers'), ('crate_warehouses', 'Crate Warehouses'), ('executive_office_garages', 'Executive Office Garages'), ('executive_offices', 'Executive Offices'), ('facilities', 'Facilities'), ('garages', 'Garages'), ('hangers', 'Hangers'), ('mc_businesses', 'MC Businesses'), ('mc_clubhouses', 'MC Clubhouses'), ('nightclubs', 'Nighclubs'), ('vehicle_warehouses', 'Vehicle Warehouses'), ('yachts', 'Yachts')], max_length=70)),
                ('state', models.CharField(choices=[('blaine_county', 'Blaine County'), ('downtown_los_santos', 'Downtown Los Santos'), ('east_los_santos', 'East Los Santos'), ('north_los_santos', 'North Los Santos'), ('south_los_santos', 'South Los Santos'), ('west_los_santos', 'West Los Santos')], max_length=70)),
                ('available_from', models.CharField(blank=True, choices=[('dynasty8_real_estate', 'Dynasty 8 Real Estate'), ('maze_bank_foreclosures', 'Maze Bank Foreclosures'), ('securoserv', 'SecuroServ'), ('the_open_road', 'The Open Road'), ('dynasty8_executive', 'Dynasty 8 Executive'), ('war_stock_cache_carry', 'Warstock Cache & Carry'), ('dock_tease', 'DockTease'), ('diamond_casino_resort', 'The Diamond Casino & Resort'), ('arena_war_tv', 'ArenaWar.tv')], max_length=50, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(1)])),
                ('vehicle_capacity', models.PositiveSmallIntegerField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('game_edition_mode', models.CharField(blank=True, choices=[('gta_online', 'GTA Online'), ('story_mode', 'Story Mode'), ('returning_player_bonus', 'Returning Player Bonus'), ('criminal_enterprise_starter_pack', 'Criminal Enterprise Starter Pack'), ('mission_only', 'Mission Only'), ('collectors_edition', 'Collectors Edition'), ('all_editions', 'All Editions')], max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
