# Generated by Django 3.1.1 on 2020-09-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='based_on',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='based_on',
            field=models.ManyToManyField(help_text="Reallife vehicle it's based on", to='vehicles.RealLifeVehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='game_edition_mode',
            field=models.CharField(blank=True, choices=[('gta_online', 'GTA Online'), ('story_mode', 'Story Mode'), ('returning_player_bonus', 'Returning Player Bonus'), ('criminal_enterprise_starter_pack', 'Criminal Enterprise Starter Pack'), ('mission_only', 'Mission Only'), ('collectors_edition', 'Collectors Edition'), ('all_editions', 'All Editions')], help_text='Game Edition/Mode', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='resale_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max sell value if purchased', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='stolen_sell_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max sell value if stolen', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_class',
            field=models.CharField(choices=[('boats', 'Boats'), ('commercial', 'Commercial'), ('compacts', 'Compacts'), ('coupes', 'Coupes'), ('cycles', 'Cycles'), ('emergency', 'Emergency'), ('helicopters', 'Helicopters'), ('industrial', 'Industrial'), ('military', 'Military'), ('motorcycles', 'Motorcycles'), ('muscle', 'Muscle'), ('offroad', 'Off-road'), ('openwheel', 'Open-wheel'), ('planes', 'Planes'), ('sedan', 'Sedan'), ('service', 'Service'), ('sports', 'Sports'), ('sport_classic', 'Sport Classic'), ('super', 'Super'), ('suv', 'SUV'), ('utility', 'Utility'), ('vans', 'Vans')], max_length=70),
        ),
    ]
