# Generated by Django 3.1.1 on 2020-09-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='num_doors',
            new_name='capacity',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='game_edition',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='game_edition_mode',
            field=models.CharField(blank=True, help_text='Game Edition/Mode', max_length=20, null=True, verbose_name=(('gta_online', 'GTA Online'), ('story_mode', 'Story Mode'), ('returning_player_bonus', 'Returning Player Bonus'), ('criminal_enterprise_starter_pack', 'Criminal Enterprise Starter Pack'), ('mission_only', 'Mission Only'), ('collectors_edition', 'Collectors Edition'), ('all_editions', 'All Editions'))),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='special_features',
            field=models.CharField(blank=True, choices=[('arena_contender', 'Arena Contender'), ('armed', 'Armed Vehicle'), ('armored', 'Armored Vehicle'), ('covertible_hard_top', 'Covertible Hard Top'), ('convertible_soft_top', 'Covertible Soft Top'), ('custom_vehicle', 'Custom Vehicle'), ('electric', 'Electric Vehicle'), ('float_water', 'Float on Water'), ('flying_ability', 'Flying Ability'), ('gang_vehicle', 'Gang Vehicle'), ('hover_ability', 'Hover Ability'), ('kers_boost', 'KERS Boost'), ('remote_controlled', 'Remote Controlled'), ('rocket_boost', 'Rocket Boost'), ('special_vehicle', 'Special Vehicle'), ('submersible', 'Submersible'), ('towing_hitch', 'Towing Hitch'), ('vehicle_workshop', 'Vehicle Workshop'), ('weaponized', 'Weaponized Vehicle')], max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='storage_location',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='storage_location',
            field=models.ManyToManyField(to='vehicles.VehicleStorageLocation'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_class',
            field=models.CharField(max_length=70, verbose_name=(('boats', 'Boats'), ('commercial', 'Commercial'), ('compacts', 'Compacts'), ('coupes', 'Coupes'), ('cycles', 'Cycles'), ('emergency', 'Emergency'), ('helicopters', 'Helicopters'), ('industrial', 'Industrial'), ('military', 'Military'), ('motorcycles', 'Motorcycles'), ('muscle', 'Muscle'), ('offroad', 'Off-road'), ('openwheel', 'Open-wheel'), ('planes', 'Planes'), ('sedan', 'Sedan'), ('service', 'Service'), ('sports', 'Sports'), ('sport_classic', 'Sport Classic'), ('super', 'Super'), ('suv', 'SUV'), ('utility', 'Utility'), ('vans', 'Vans'))),
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='workshop',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='workshop',
            field=models.ManyToManyField(help_text='Workshop for modifying vehicle', to='vehicles.VehicleWorkshop'),
        ),
    ]
