# Generated by Django 3.1.1 on 2020-09-20 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20200919_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='based_on',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='storage_location',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='workshop',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='real_life_vehicles',
            field=models.ManyToManyField(help_text="Reallife vehicle it's based on", related_name='vehicles', to='vehicles.RealLifeVehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='storage_locations',
            field=models.ManyToManyField(related_name='vehicles', to='vehicles.VehicleStorageLocation'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='workshops',
            field=models.ManyToManyField(help_text='Workshop for modifying vehicle', related_name='vehicles', to='vehicles.VehicleWorkshop'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.vehiclemanufacturer'),
        ),
    ]
