# Generated by Django 3.1.1 on 2020-09-21 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_auto_20200920_2000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RealLifeVehicle',
            new_name='VehicleInspirer',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='top_speed',
            new_name='top_speed_mph',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='real_life_vehicles',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='resale_value',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='sell_ability',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='stolen_sell_value',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='resell_value_purchased',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='resell_value_stolen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='sellability',
            field=models.CharField(blank=True, choices=[('purchased_high_end', 'Purchased High End'), ('purchased_or_stolen', 'Purchased Or Stolen'), ('only_stolen', 'Only Stolen'), ('not_sellable', 'Can not Be Sold')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_inspirers',
            field=models.ManyToManyField(related_name='vehicles', to='vehicles.VehicleInspirer'),
        ),
    ]
