# Generated by Django 3.1.1 on 2020-09-21 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_auto_20200921_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleManufacturerRealLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=70, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleRealLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=70, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_inspirers',
        ),
        migrations.AlterField(
            model_name='vehiclemanufacturer',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiclestoragelocation',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicleworkshop',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.DeleteModel(
            name='VehicleInspirer',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_real_life',
            field=models.ManyToManyField(related_name='vehicles', to='vehicles.VehicleRealLife'),
        ),
        migrations.AddField(
            model_name='vehiclemanufacturer',
            name='manufacturer_real_life',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_manufacturer', to='vehicles.vehiclemanufacturerreallife'),
        ),
    ]
