# Generated by Django 3.1.1 on 2020-09-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_auto_20200921_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_real_life',
            new_name='vehicles_real_life',
        ),
    ]
