# Generated by Django 3.1.1 on 2020-09-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_auto_20200921_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='game_edition_mode',
            field=models.CharField(blank=True, choices=[('gta_online', 'GTA Online'), ('story_mode', 'Story Mode'), ('returning_player_bonus', 'Returning Player Bonus'), ('criminal_enterprise_starter_pack', 'Criminal Enterprise Starter Pack'), ('mission_only', 'Mission Only'), ('collectors_edition', 'Collectors Edition'), ('all_editions', 'All Editions')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='workshops',
            field=models.ManyToManyField(related_name='vehicles', to='vehicles.VehicleWorkshop'),
        ),
    ]
