# Generated by Django 3.1.1 on 2020-09-21 12:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=70, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponRealLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=70, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=70, unique=True)),
                ('ammo_capacity', models.PositiveSmallIntegerField()),
                ('extended_ammo', models.PositiveSmallIntegerField()),
                ('weapon_type', models.CharField(choices=[('handguns', 'Handguns'), ('shotguns', 'Shotguns'), ('machine_guns', 'Machine Guns'), ('assault_rifles', 'Assault Rifles'), ('heavy_weapons', 'Heavy Weapons'), ('thrown_weapons', 'Thrown Weapons'), ('melee', 'Melee'), ('mounted_weapons', 'Mounted Weapons')], max_length=70)),
                ('available_from', models.CharField(blank=True, choices=[('ammu_nation', 'Ammu Nation'), ('weapon_workshop', 'Weapon Workshop'), ('stolen_found', 'Is Stolen/Found'), ('bonus_reward', 'Bonus Reward'), ('unacquirable', 'Cannot be acquired'), ('merry_weather_security_services', 'Merry Weather Security Services')], max_length=50, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(1)])),
                ('modifications', models.CharField(blank=True, choices=[('can_be_modified', 'Can be modified'), ('cannot_be_modified', 'Cannot be modified')], max_length=50, null=True)),
                ('game_edition_mode', models.CharField(blank=True, choices=[('gta_online', 'GTA Online'), ('story_mode', 'Story Mode'), ('returning_player_bonus', 'Returning Player Bonus'), ('criminal_enterprise_starter_pack', 'Criminal Enterprise Starter Pack'), ('mission_only', 'Mission Only'), ('collectors_edition', 'Collectors Edition'), ('all_editions', 'All Editions')], max_length=50, null=True)),
                ('damage_rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('firing_rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('accuracy_rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('range_rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('clip_size_rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='weapons.weaponmanufacturer')),
                ('weapon_real_life', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weapons', to='weapons.weaponreallife')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
